#source common.sh
#print_head Copy MongoDB repo file
#cp mongo.repo /etc/yum.repos.d/mongo.repo &>> $log_file
#
#print_head Install MongoDB
#dnf install mongodb-org -y &>> $log_file
#
#print_head Update MongoDB config file
#sed -i -e 's|127.0.0.1|0.0.0.0|' /etc/mongod.conf &>> $log_file
#
#print_head Start MongoDB Service
#systemctl enable mongod &>> $log_file
#systemctl restart mongod &>> $log_file


- name: Copy Mongodb Repo file
  ansible.builtin.copy:
  src: mongo.repo
  dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb
  ansible.builtin.dnf:
  state: Installed

- name: Update Mongodb config file listen address
  ansible.builtin.replace:
  path: /etc/mongod.conf
  regexp: '127.0.0.1'
  replace: '0.0.0.0'

- name: Start Mongodb Service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: yes

